### ISSUE TITLE
Websocket调用API会出现JSON解析错误

### ISSUE THREAD

**Issue by Mrs4s** [frankli0324/cqhttp.Cyan#3]

**Comment by frankli0324** [comment]
我想了半天，我觉得大概是你没填access token...

**Comment by frankli0324** [comment]
我加了个检查access token 对不对的 exception

**Comment by Mrs4s** [comment]
问题是我参数完全不改 用http通信就不会是这个问题，我看报错似乎是消息末多了个未知字符。
抓包看到ws返回的消息长度比解析错误的pos少一位。

**Comment by frankli0324** [comment]
> 问题是我参数完全不改 用http通信就不会是这个问题，我看报错似乎是消息末多了个未知字符。
> 抓包看到ws返回的消息长度比解析错误的pos少一位。

能发一下出问题的代码么？
我这没问题。。

**Comment by Mrs4s** [comment]
![image](https://user-images.githubusercontent.com/12137562/54920434-3529a880-4f3e-11e9-9b5d-86aefa80bfa7.png)
![image](https://user-images.githubusercontent.com/12137562/54920306-e0862d80-4f3d-11e9-9188-3ed83c9a4fa2.png)
可以看到出错的位置比接收到的实际长度要多，怀疑可能是编码之类的问题。

**Comment by frankli0324** [comment]
这是个发送消息的调用？

**Comment by Mrs4s** [comment]
这个是GetGroupList的调用
我QQ是1844812067

**Comment by frankli0324** [comment]
暂时在 [commit f05b3a4](https://github.com/frankli0324/cqhttp.Cyan/commit/f05b3a465fa26fe84b459454f5d234f72bf7a820)中修复了
